CREATE DATABASE todolist;

CREATE TABLE IF NOT EXISTS `todos` (
  id INT NOT NULL AUTO_INCREMENT,
  title TEXT NOT NULL,
  checked TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY(id)
);